blank_issues_enabled: false
pull_request_templates:
  - name: "💜 Feature 추가"
    path: PULL_REQUEST_TEMPLATE/feature.md
  - name: "🐞 Bugfix 수정"
    path: PULL_REQUEST_TEMPLATE/bugfix.md
  - name: "🔄 Refactor 리팩토링"
    path: PULL_REQUEST_TEMPLATE/refactor.md
